# Review

## [Dataset](https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic))

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv( 'https://archive.ics.uci.edu/ml/''machine-learning-databases''/breast-cancer-wisconsin/wdbc.data', header=None)

In [3]:
# Let's check the dataframe

In [5]:
# note that the target variable is the first column

__Problem__


__Goal__



In [1]:
## Dummy Model Accuracy Rate (Baseline)



In [8]:
# How many 'M''s and 'B''s?

In [2]:
# How is the ratio of 'B' and 'M'



In [10]:
# Convert target variables into numerical data

Using sklearn modules allows us to __fit__ the transformations only on `training data` and only transform the `test_data`.

In [17]:
# Missing Values?

## EDA

## Data Cleaning

## Data Preparation

__Splitting Data__

In [19]:
## use train-test split


In [23]:
import numpy as np

__Data Leakage Example__

__Correct Way of Scaling Data__

In [5]:
## suppose
#data_train = np.array([1,2,3])


## future data 


In [6]:
# training_mean = data_train.mean()
# training_std = data_train.std()

# training_scaled = (data_train -  training_mean)/training_std

In [7]:
# test_scaled?

__Scaling data__

In [35]:
## Standard scale data

In [8]:
 ## training_mean and std calculated
 ## only use training mean and std


## Never fit onto Test data!! Only Transform


__Creating New Features__

In [39]:
from sklearn.preprocessing import PolynomialFeatures

## Modeling

### Logistic Regression

__With No regularization__ (Vanilla Log Reg)

In [46]:
## import Logistic regression

In [48]:
## instantiate LR with no penalty

In [50]:
## fit model

In [9]:
## learned the coefficients

In [11]:
#score ## accuracy

In [54]:
## from sklearn.metrics import confusion_matrix

In [56]:
## create a confusion matrix

In [58]:
## visualize confusion matrix with utils.py plot_confusion_matrix

In [59]:
import utils

__Validation__

In [62]:
## import -- from sklearn.model_selection import cross_validate

In [64]:
## call cross-validate with return_train_score, return estimator, cv =5

In [67]:
## investigate cv results

In [70]:
## Print results and keep them somewhere

In [13]:
#print('Vanilla Regression 5-fold cv results (Accuracy) %.3f +/- %.3f'%(validation_mean, validation_std))

In [14]:
## note that we could use other scoring options in cross_validate

[Cross_validate - Scoring](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html#sklearn.model_selection.cross_validate)

In [15]:
# cv_fivefold = cross_validate(estimator= lr, 
#                              X = X_train_scaled,
#                              y = y_train,
#                              cv = 5,
#                              scoring = 'recall',
#                              return_train_score= True, 
#                              return_estimator= True, verbose = 2)

In [16]:
#cv_fivefold['test_score'] ## recall scores

In [17]:
## note that sklearn has many other metric you can use

In [18]:
## from sklearn.metrics import recall_score, precision_score, roc_auc_score

### Logistic Regression with Regularization

In [77]:
## check the Logistic regression module again

__With regularization scaling is necessary__

__Grid Search Validation__

In [85]:
## import GridSerachCV from sklearn.model_selection

In [87]:
## prepare a grid with 'C' and 'penalty'

In [90]:
## instantiate the gridsearch

In [92]:
## fit grid search

In [94]:
## check gridsearch cv_results_

## we can make them a dataframe also

In [97]:
## print best parameters

In [98]:
## cross_validate the best estimator_

In [102]:
## pretty print test scores

In [103]:
## fit best regularization logreg and plot the confusion matrix

In [19]:
# validation_mean = cv_fivefold['test_score'].mean()

# validation_std = cv_fivefold['test_score'].std()

# print('Regularized Log Regression 5-fold cv results (Accuracy) %.3f =/- %.3f'%(validation_mean, validation_std))

## Decision Trees

In [105]:
## import decisiontree classifier

In [106]:
## instantiate

In [107]:
from sklearn.tree import DecisionTreeClassifier

In [108]:
dt_clf = DecisionTreeClassifier()

dt_clf.fit(X_train, y_train)

dt_clf.score(X_train, y_train)


1.0

In [109]:
## cross_validate

In [110]:
cv_fivefold = cross_validate(estimator= dt_clf, 
                             X = X_train_scaled,
                             y = y_train,
                             cv = 5,
                             return_train_score= True, 
                             return_estimator= True, 
                             verbose = 2)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV]  ................................................................
[CV] ................................................. , total=   0.0s
[CV]  ................................................................
[CV] ................................................. , total=   0.0s
[CV]  ................................................................
[CV] ................................................. , total=   0.0s
[CV]  ................................................................
[CV] ................................................. , total=   0.0s
[CV]  ................................................................
[CV] ................................................. , total=   0.0s


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished


In [111]:
cv_fivefold['test_score']

array([0.92307692, 0.92307692, 0.92307692, 0.94505495, 0.91208791])

In [112]:
cv_fivefold['train_score']

array([1., 1., 1., 1., 1.])

__Overfitting__

In [113]:
## confusion matrix plot

## Random Forests

### Bootstrapping

<img src= "images/bootstrap1.png" style="height:450px">


### Bagging: Bootstrap Aggregation


__Core idea__

- Decision trees have high variance.

- We know averaging can reduce the variance. (Central Limit Theorem?)

- Why bootstrap though?

    - Averaging the same numbers yields the same number: [2,2,2,2]  --> avg: 2
    
    - You want each tree to learn a little bit differently so that averaging make sense.

__A little bit more details__


We will use this idea calculate $$ \hat{f}^{1}(x), \cdots, \hat{f}^{B}(x)$$ where each $\hat{f}^{i}$ represents a decision tree fitted to the bootstrapped data.

Then we will make a prediction by: 

$$ \hat{f}_{\text{avg}}(x) = \frac{1}{B}\sum_{b=1}^{B} \hat{f}^{b}(x)$$

Note that this is for regression and for the classification we can get majority vote.

[sklearn averages over probabilities not majority vote](https://scikit-learn.org/stable/modules/ensemble.html#forest)


__Problem__ We still have some problem with this approach and random forests will address this problem. Can you see the issue?

- If we have a strong predictor then this will dominate in each tree.

Hint: Correlated trees

- Random forests adds some randomness into the procedure to make each tree uncorrolated.

### Implementation of Random Forest

In [114]:
from sklearn.ensemble import RandomForestClassifier

In [115]:
X_train.shape

(455, 30)

In [116]:
np.log(30)

3.4011973816621555

In [117]:
rf = RandomForestClassifier(n_estimators= 700, max_features='auto', max_depth= 10)

In [118]:
cv_fivefold = cross_validate(estimator= rf, 
                             X = X_train_scaled,
                             y = y_train,
                             cv = 5,
                             return_train_score= True, 
                             return_estimator= True, 
                             verbose = 2)

[CV]  ................................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................................. , total=   1.0s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.0s remaining:    0.0s


[CV] ................................................. , total=   0.9s
[CV]  ................................................................
[CV] ................................................. , total=   1.0s
[CV]  ................................................................
[CV] ................................................. , total=   0.9s
[CV]  ................................................................
[CV] ................................................. , total=   0.9s


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    4.9s finished


In [119]:
cv_fivefold['test_score']

array([0.95604396, 0.97802198, 0.97802198, 0.95604396, 0.96703297])

In [120]:
validation_mean = cv_fivefold['test_score'].mean()

validation_std = cv_fivefold['test_score'].std()

print('Random Forest 5-fold cv results (Accuracy) %.3f =/- %.3f'%(validation_mean, validation_std))

Random Forest 5-fold cv results (Accuracy) 0.967 =/- 0.010


In [121]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_train)
score = rf.score(X_train, y_train)
cm = confusion_matrix(y_train, y_pred)

In [21]:
## confusion matrix

__Roc Curves__

In [22]:
# import matplotlib.pyplot as plt  # doctest: +SKIP
# from sklearn import datasets, metrics, model_selection, svm

# rf.fit(X_train, y_train)

# rfc_disp = metrics.plot_roc_curve(rf, X_test, y_test)  # doctest: +SKIP
# log_disp = metrics.plot_roc_curve(lr, X_test_scaled, y_test, ax = rfc_disp.ax_)  # doctest: +SKIP
# dct_disp = metrics.plot_roc_curve(dt_clf, X_test, y_test, ax = rfc_disp.ax_)  # doctest: +SKIP

# rfc_disp.figure_.suptitle("ROC curve comparison")
# plt.show()  

## Best Model and Model Evaluation

In [ ]:
lr = LogisticRegression(C = 0.1, penalty = 'l2', solver = 'saga', max_iter= 10000)

lr.fit(X_train_scaled, y_train)
score = lr.score(X_test_scaled, y_test)

In [ ]:
y_pred = lr.predict(X_test_scaled)

In [ ]:
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

In [ ]:
score

In [ ]:
utils.plot_confusion_matrix(cm, score)

### Extra Material 

- [Sklearn averages probabilities in RF implementation](https://scikit-learn.org/stable/modules/ensemble.html#forest)

- [On the variance](https://newonlinecourses.science.psu.edu/stat414/node/167/)

- [Do RF immune to overfitting?](https://en.wikipedia.org/wiki/Talk%3ARandom_forest)

- [Tricky stuff with respect to feature importance](http://rnowling.github.io/machine/learning/2015/08/10/random-forest-bias.html)

- [An interesting implementation of feature importance](https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances_faces.html#sphx-glr-auto-examples-ensemble-plot-forest-importances-faces-py)

- [Different Ensemble Methods in sklearn](https://scikit-learn.org/stable/modules/ensemble.html#forest)

- [ISLR - section 8.2](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)

- [Another library for RF: H2o](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/drf.html)